#!/bin/bash

set -euo pipefail

# ============================================================
# NOVA - WEB Init Script
# Golden Image : npc-tb-golden-web-v1
# Role         : WEB
#
# GitHub       : bespin-nova/WEB
# Source       : WEB/web/
# GCS          : gs://npc-bucket-nova/web/
# ============================================================


# ------------------------------------------------------------
# Environment
# ------------------------------------------------------------

BUCKET_NAME="npc-bucket-nova"
WEB_BUCKET_PATH="web"

WEB_ROOT="/var/www/html"
TEMP_DIR="/tmp/nova-web"

INTERNAL_LB_IP="192.168.20.100"
INTERNAL_LB_PORT="8080"

PROXY_CONF="/etc/httpd/conf.d/petclinic-proxy.conf"
CACHE_CONF="/etc/httpd/conf.d/cache-control.conf"
ERROR_CONF="/etc/httpd/conf.d/error-pages.conf"


echo "========================================"
echo " NOVA WEB Initialization Start"
echo "========================================"


# ------------------------------------------------------------
# 1. Golden Image 환경 확인
# ------------------------------------------------------------

echo "[1/8] Checking Apache environment..."

if ! command -v httpd >/dev/null 2>&1; then
    echo "ERROR: Apache is not installed."
    exit 1
fi

HTTPD_MODULES="$(httpd -M 2>&1)"

if ! grep -q "proxy_module" <<< "${HTTPD_MODULES}"; then
    echo "ERROR: proxy_module is not enabled."
    exit 1
fi

if ! grep -q "proxy_http_module" <<< "${HTTPD_MODULES}"; then
    echo "ERROR: proxy_http_module is not enabled."
    exit 1
fi

if ! grep -q "headers_module" <<< "${HTTPD_MODULES}"; then
    echo "ERROR: headers_module is not enabled."
    exit 1
fi

echo "Apache environment OK."


# ------------------------------------------------------------
# 2. Cloud Storage → WEB 파일 다운로드
# ------------------------------------------------------------

echo "[2/8] Downloading WEB contents from Cloud Storage..."
echo "Source: gs://${BUCKET_NAME}/${WEB_BUCKET_PATH}"

rm -rf "${TEMP_DIR}"
mkdir -p "${TEMP_DIR}"

gcloud storage rsync \
    --recursive \
    "gs://${BUCKET_NAME}/${WEB_BUCKET_PATH}" \
    "${TEMP_DIR}"

# 필수 WEB 진입 파일 검증
if [ ! -f "${TEMP_DIR}/index.html" ]; then
    echo "ERROR: index.html was not downloaded."
    exit 1
fi

# 커스텀 오류 페이지 검증
if [ ! -f "${TEMP_DIR}/_error/404.html" ]; then
    echo "ERROR: _error/404.html was not downloaded."
    exit 1
fi

if [ ! -f "${TEMP_DIR}/_error/503.html" ]; then
    echo "ERROR: _error/503.html was not downloaded."
    exit 1
fi

echo "WEB contents downloaded."


# ------------------------------------------------------------
# 3. Apache DocumentRoot 배포
# ------------------------------------------------------------

echo "[3/8] Deploying WEB contents..."

# 기존 WEB 파일 제거
find "${WEB_ROOT}" \
    -mindepth 1 \
    -maxdepth 1 \
    -exec rm -rf {} +

# 다운로드한 WEB 파일 배포
cp -a "${TEMP_DIR}/." "${WEB_ROOT}/"

# Apache 소유권 설정
chown -R apache:apache "${WEB_ROOT}"

# SELinux Context 복구
restorecon -Rv "${WEB_ROOT}"

echo "WEB contents deployed."


# ------------------------------------------------------------
# 4. Reverse Proxy 설정
# ------------------------------------------------------------

echo "[4/8] Configuring Reverse Proxy..."

cat > "${PROXY_CONF}" <<EOF
# ============================================================
# NOVA - PetClinic Reverse Proxy
# Generated by WEB Init Script
# ============================================================

ProxyPreserveHost On

# WAS/Tomcat에서 반환된 오류 응답을 Apache가 처리
# 예: Tomcat 404 → Apache ErrorDocument 404
ProxyErrorOverride On

ProxyPass        /petclinic/ http://${INTERNAL_LB_IP}:${INTERNAL_LB_PORT}/petclinic/
ProxyPassReverse /petclinic/ http://${INTERNAL_LB_IP}:${INTERNAL_LB_PORT}/petclinic/
EOF

echo "Reverse Proxy configured."
echo "Target: ${INTERNAL_LB_IP}:${INTERNAL_LB_PORT}"


# ------------------------------------------------------------
# 5. Custom Error Page 설정
# ------------------------------------------------------------

echo "[5/8] Configuring Custom Error Pages..."

cat > "${ERROR_CONF}" <<'EOF'
# ============================================================
# NOVA - Custom Error Pages
# Generated by WEB Init Script
# ============================================================

# 존재하지 않는 WEB / WAS 리소스
ErrorDocument 404 /_error/404.html

# Reverse Proxy / WAS / Internal LB 장애
ErrorDocument 502 /_error/503.html
ErrorDocument 503 /_error/503.html
ErrorDocument 504 /_error/503.html
EOF

echo "Custom Error Pages configured."


# ------------------------------------------------------------
# 6. Cache-Control 설정
# ------------------------------------------------------------

echo "[6/8] Configuring Cache-Control..."

cat > "${CACHE_CONF}" <<'EOF'
# ============================================================
# NOVA - Static Content Cache Policy
# Generated by WEB Init Script
# ============================================================

<IfModule mod_headers.c>

    # HTML은 항상 최신 버전 확인
    <FilesMatch "\.(html)$">
        Header set Cache-Control "no-cache, no-store, must-revalidate"
    </FilesMatch>

    # 이미지 정적 리소스는 1일 캐시
    <FilesMatch "\.(jpg|jpeg|png|gif|svg|webp|ico)$">
        Header set Cache-Control "public, max-age=86400"
    </FilesMatch>

</IfModule>
EOF

echo "Cache-Control configured."


# ------------------------------------------------------------
# 7. Apache 설정 검증
# ------------------------------------------------------------

echo "[7/8] Validating Apache configuration..."

if ! apachectl configtest; then
    echo "ERROR: Apache configuration test failed."
    exit 1
fi

echo "Apache configuration OK."


# ------------------------------------------------------------
# 8. Apache 시작 / 재시작
# ------------------------------------------------------------

echo "[8/8] Starting Apache..."

systemctl enable httpd
systemctl restart httpd

if ! systemctl is-active --quiet httpd; then
    echo "ERROR: Apache failed to start."
    systemctl status httpd --no-pager || true
    exit 1
fi

echo "Apache is running."


# ------------------------------------------------------------
# 임시 파일 정리
# ------------------------------------------------------------

rm -rf "${TEMP_DIR}"


# ------------------------------------------------------------
# 최종 상태 출력
# ------------------------------------------------------------

echo ""
echo "========================================"
echo " NOVA WEB Initialization Complete"
echo "========================================"
echo "WEB Root        : ${WEB_ROOT}"
echo "GCS Source      : gs://${BUCKET_NAME}/${WEB_BUCKET_PATH}"
echo "Internal LB     : ${INTERNAL_LB_IP}:${INTERNAL_LB_PORT}"
echo "PetClinic Proxy : /petclinic/"
echo "Error 404       : /_error/404.html"
echo "Error 5xx       : /_error/503.html"
echo "========================================"


# ------------------------------------------------------------
# 기본 WEB 확인
# ------------------------------------------------------------

echo ""
echo "[CHECK] Static WEB"

curl -I \
    --connect-timeout 5 \
    http://localhost/ || true


# ------------------------------------------------------------
# Custom Error Page 파일 확인
# ------------------------------------------------------------

echo ""
echo "[CHECK] Custom 404 Page"

curl -I \
    --connect-timeout 5 \
    http://localhost/_error/404.html || true

echo ""
echo "[CHECK] Custom 503 Page"

curl -I \
    --connect-timeout 5 \
    http://localhost/_error/503.html || true


# ------------------------------------------------------------
# Apache 404 처리 확인
# ------------------------------------------------------------

echo ""
echo "[CHECK] Apache Custom 404"

curl -I \
    --connect-timeout 5 \
    http://localhost/nova-page-does-not-exist || true


# ------------------------------------------------------------
# Reverse Proxy 확인
# ------------------------------------------------------------

echo ""
echo "[CHECK] PetClinic Reverse Proxy"

curl -I \
    --connect-timeout 5 \
    http://localhost/petclinic/ || true


echo ""
echo "Initialization finished successfully."